BitError: change to not be abstract and add default report() method (#3239)
* BitError: change to not be abstract and add default report() method

* change exceptions extensions from tsx to ts